from enum import Enum


class SystemState(str, Enum):
    INITIALIZING = "INITIALIZING"
    READY = "READY"
    WAIT_OBJECT = "WAIT_OBJECT"
    CONVEYOR_TO_INSPECTION = "CONVEYOR_TO_INSPECTION"
    CONVEYOR_MOVE = "CONVEYOR_MOVE"
    STRUCTURED_LIGHT_SCAN = "STRUCTURED_LIGHT_SCAN"
    PLAN_POSES = "PLAN_POSES"
    MOVE_SAFE_POSE = "MOVE_SAFE_POSE"
    AUTO_Z_SEARCH = "AUTO_Z_SEARCH"
    SURFACE_INSPECTION = "SURFACE_INSPECTION"
    ANOMALY_INSPECTION = "ANOMALY_INSPECTION"
    NEXT_POSE = "NEXT_POSE"
    FINALIZE = "FINALIZE"
    CONVEYOR_OUT = "CONVEYOR_OUT"
    COMPLETE = "COMPLETE"
    ERROR = "ERROR"
    STOPPED = "STOPPED"
