from __future__ import annotations

from typing import Protocol


class ConveyorController(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def move_to_inspection(self) -> None: ...
    def move_out(self) -> None: ...
    def wait_until_stopped(self, timeout: float | None = None) -> None: ...
